### ISSUE TITLE
Train Error

### ISSUE THREAD

**Issue by gourdchen** [Ryo-Ito/brain_segmentation#15]
when I use the " python train.py  -f dataset_train.json " the train the network, I got this messages:

```
Namespace(gpu=-1, input_file='dataset_train.json', input_shape=[80, 80, 80], iteration=10000, learning_rate=0.001, monitor_step=1000, n_batch=1, n_tiles=[5, 5, 5], out='vrn.npz', output_shape=[60, 60, 60], validation_file=None, weight_decay=0.0005)
D:\Develope\brain_segmentation\utils.py:68: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  mask[slices] *= 2
D:\Develope\brain_segmentation\utils.py:79: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  image_patch = image[input_slices]
D:\Develope\brain_segmentation\utils.py:80: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  label_patch = label[output_slices]
Traceback (most recent call last):
  File "train.py", line 169, in <module>
    main()
  File "train.py", line 111, in main
    logits = [logit[slices_in] for logit in logits]
  File "train.py", line 111, in <listcomp>
    logits = [logit[slices_in] for logit in logits]
  File "C:\Anaconda3\envs\brain\lib\site-packages\chainer\functions\array\get_item.py", line 89, in get_item
    return GetItem(slices)(x)
  File "C:\Anaconda3\envs\brain\lib\site-packages\chainer\function.py", line 200, in __call__
    outputs = self.forward(in_data)
  File "C:\Anaconda3\envs\brain\lib\site-packages\chainer\functions\array\get_item.py", line 44, in forward
    return utils.force_array(ary[self.slices]),
TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by gourdchen** [comment]
i have solved this problem
